### ISSUE TITLE
exportOctreeGrid does not work!

### ISSUE THREAD

**Issue by 461353349** [Tonsty/OctreeBSplines#1]
I set  --octree 1 in the commandline, function exportOctreeGrid will execute.

I donnot know how to set, the code in the while will execute and octree.vtk will generate.

Can you help me? Thank you.

**Comment by Tonsty** [comment]
@461353349  It is indeed a bug of the released executable in CASD_vs2010_executable.rar.
Please compile the latest commit or use the new release https://www.dropbox.com/s/qs7u1lvca0be1c3/CASD_vs2010_executable_octree_bug_fix.rar?dl=0

**Comment by 461353349** [comment]
Thanks.  I didnot find the new source code. Can you submit them to github?

**Comment by Tonsty** [comment]
@461353349 I have submitted the newest source code to github. 
It is just the the latest commit in the "master" branch.

**Comment by 461353349** [comment]
OK, I see.  
Github need some time to update itself.  I would see your newest code tomorrow. Thanks a lot!

**Comment by 461353349** [comment]
Hi, I have checked the code on the Github, "Latest commit 524358e  on 30 Aug 2017", Can you check it?

**Comment by 461353349** [comment]
Hi, I have checked the code on the Github, "Latest commit 524358e on 30 Aug 2017", Can you check it?

**Comment by Tonsty** [comment]
@461353349 have you tried the executable https://www.dropbox.com/s/qs7u1lvca0be1c3/CASD_vs2010_executable_octree_bug_fix.rar?dl=0，
it is compiled from the latest commit 524358e

**Comment by 461353349** [comment]
It is my fault. 
I have set octree as 1, not 4. 
I am sorry for the trouble I have caused you.
